// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $punjab_api_forms_getOfflineForm_link_ from "./routes/punjab/category/api/forms/getOfflineForm/[link].ts";
import * as $punjab_api_forms_index from "./routes/punjab/category/api/forms/index.ts";
import * as $punjab_index from "./routes/punjab/index.tsx";
import * as $dropdown_selections_pb from "./islands/dropdown-selections-pb.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/punjab/api/forms/getOfflineForm/[link].ts":
      $punjab_api_forms_getOfflineForm_link_,
    "./routes/punjab/api/forms/index.ts": $punjab_api_forms_index,
    "./routes/punjab/index.tsx": $punjab_index,
  },
  islands: {
    "./islands/dropdown-selections-pb.tsx": $dropdown_selections_pb,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
