FROM denoland/deno:1.45.2

ARG GIT_REVISION
ENV DENO_DEPLOYMENT_ID=${GIT_REVISION}
ENV MONGO_URI=${MONGO_URI}

WORKDIR /forms

COPY . .
RUN deno cache main.ts
RUN deno run -A dev.ts build

EXPOSE 8000

CMD ["run", "-A", "main.ts"]
